# 6.2 Parameter Management

In [2]:
import torch
from torch import nn

net = nn.Sequential(nn.LazyLinear(8), nn.ReLU(), nn.LazyLinear(1))

X = torch.randn(size=(2, 4))
net(X).shape

/home/solee/miniconda3/envs/dive2dl/lib/python3.7/site-packages/torch/nn/modules/lazy.py:180: UserWarning: Lazy modules are a new feature under heavy development so changes to the API or functionality can happen at any moment.
  warnings.warn('Lazy modules are a new feature under heavy development '


torch.Size([2, 1])

## 6.2.1 Parameter Access

In [3]:
print(net[2].state_dict())
print(type(net[2].bias))
print(net[2].bias.data)
print(net[2].weight.grad == None)

[(name, param.shape) for name, param in net.named_parameters()]

OrderedDict([('weight', tensor([[ 0.0477,  0.0158,  0.1470, -0.1604, -0.3308,  0.0406, -0.1773, -0.2789]])), ('bias', tensor([0.0949]))])
<class 'torch.nn.parameter.Parameter'>
tensor([0.0949])
True


[('0.weight', torch.Size([8, 4])),
 ('0.bias', torch.Size([8])),
 ('2.weight', torch.Size([1, 8])),
 ('2.bias', torch.Size([1]))]

## 6.2.2 Tied Parameters

In [11]:
shared = nn.LazyLinear(8)
net = nn.Sequential(nn.LazyLinear(8), nn.ReLU(), shared, nn.ReLU(), shared, nn.ReLU(), nn.LazyLinear(1))
net(X)
print(net[2].weight.data[0] == net[4].weight.data[0])
net[2].weight.data[0, 0] = 100
print(net[2].weight.data[0] == net[4].weight.data[0])

tensor([True, True, True, True, True, True, True, True])
tensor([True, True, True, True, True, True, True, True])


/home/solee/miniconda3/envs/dive2dl/lib/python3.7/site-packages/torch/nn/modules/lazy.py:180: UserWarning: Lazy modules are a new feature under heavy development so changes to the API or functionality can happen at any moment.
  warnings.warn('Lazy modules are a new feature under heavy development '
